### ISSUE TITLE
Module link

### ISSUE THREAD

**Issue by zecojls** [zecojls/tagee#5]
Hey @s-kganz,

I had to copy the TAGEE module to my new Earth Engine account (zecojls) because I lost access to my previous one when I left uni.

So the module call in the code editor is now:

`var TAGEE = require('users/zecojls/TAGEE:TAGEE-functions');`

I updated the README md and HTML files to accommodate the new paths, but should we push it to the pip page to sync the changes? Could you check that, please?

Thx

**Comment by s-kganz** [comment]
Yeah I think that is a good idea. Just uploaded the new version, see #6 (I had to modify setup.py).

**Comment by zecojls** [comment]
Thank you @s-kganz :)
